-- Standalone local-only regression suite: account isolation, sharing, deletion and source budgets.
\set ON_ERROR_STOP 1
\set QUIET 1
\ir lib/supabase_stub.sql
insert into auth.users(id,email) values
 ('00000000-0000-4000-8000-000000000001','one@example.invalid'),
 ('00000000-0000-4000-8000-000000000002','two@example.invalid');
grant execute on function public.expect(boolean,text),public.act_as(text) to authenticated,anon;
set role authenticated;
select act_as('00000000-0000-4000-8000-00000000000a');
select configure_jornada_budget_guard(encode(extensions.digest('synthetic-server-proof-over-thirty-two-characters','sha256'),'hex'));
select ai_save_provider('groq',true,'Owner main','','','','v1.owner-main','main');
select ai_save_route('assistente','groq',null,'auto:rapido',true,'fixed','[]');
select ai_save_provider('elevenlabs',true,'Owner voice','','','','v1.owner-voice','voic');
select ai_save_route('voz','elevenlabs',null,'auto:rapido',true,'fixed','[]');
select expect(not (ai_my_keys()->>'baseEnabled')::boolean,'shared base is off by default');
select ai_my_key_save('synthetic-server-proof-over-thirty-two-characters','gemini','v1.owner-personal','opay',true,'paid');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','voz')->>'provider'='elevenlabs','personal text key cannot replace owner voice');
select expect(ai_runtime('assistente')->>'source_id'='provider:groq','admin diagnostic still tests the configured route');
select act_as('00000000-0000-4000-8000-000000000001');
select expect(jsonb_array_length(ai_my_keys()->'keys')=0,'owner personal keys are hidden from members');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente') is null,'no implicit owner API inheritance');
do $$ begin perform ai_my_key_save('wrong-proof-over-thirty-two-characters','groq','v1.member-one','one',true,'no_training'); raise exception 'FALHA: key save accepted wrong server proof'; exception when insufficient_privilege then null; end $$;
select ai_my_key_save('synthetic-server-proof-over-thirty-two-characters','groq','v1.member-one','one',true,'no_training');
select expect(ai_my_keys()::text not like '%v1.member-one%' and ai_my_keys()::text not like '%user_id%','metadata contains neither ciphertext nor account selection');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')->>'key_ciphertext'='v1.member-one','runtime selects this member personal key');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')->>'source'='personal','runtime labels personal budget source');
select expect(ai_runtime('assistente') is null,'browser legacy runtime cannot read shared ciphertext');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','voz') is null,'text key does not pretend to support live voice');
do $$ begin perform ai_runtime_for_current('wrong-proof-over-thirty-two-characters','assistente'); raise exception 'FALHA: runtime without server proof'; exception when insufficient_privilege then null; end $$;
do $$ begin perform count(*) from private.ai_user_keys; raise exception 'FALHA: direct personal vault access'; exception when insufficient_privilege then null; end $$;
do $$ begin perform ai_set_member_base(true); raise exception 'FALHA: member enabled owner base'; exception when insufficient_privilege then null; end $$;
do $$ begin perform ai_remove_provider('groq'); raise exception 'FALHA: member removed owner key'; exception when insufficient_privilege then null; end $$;
select ai_my_key_save('synthetic-server-proof-over-thirty-two-characters','gemini','v1.free-gemini','free',false,null);
do $$ begin perform ai_my_key_set('gemini',true); raise exception 'FALHA: unpaid Gemini activated'; exception when invalid_parameter_value then null; end $$;
do $$ begin perform ai_my_key_save('synthetic-server-proof-over-thirty-two-characters','gemini','v1.unpaid','free',true,'no_training'); raise exception 'FALHA: unpaid Gemini enabled via save'; exception when invalid_parameter_value then null; end $$;
select ai_my_key_save('synthetic-server-proof-over-thirty-two-characters','xai','v1.xai-personal','xkey',true,'no_training');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','voz')->>'provider'='xai','member own xAI can carry native voice');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','voz')->>'model'='grok-voice-latest','voice candidate uses live model rather than text alias');
select act_as('00000000-0000-4000-8000-000000000002');
select expect(jsonb_array_length(ai_my_keys()->'keys')=0,'second account cannot list first account keys');
select expect(ai_my_key_runtime('synthetic-server-proof-over-thirty-two-characters','groq') is null,'second account cannot test first account key');
do $$ begin perform ai_my_key_remove('groq'); raise exception 'FALHA: second account removed first key'; exception when no_data_found then null; end $$;
select act_as('00000000-0000-4000-8000-00000000000a');
select expect(jsonb_array_length(ai_my_keys()->'keys')=1,'owner cannot list members personal keys');
select ai_set_member_base_source('groq',null,'no_training');
select ai_set_member_base(true);
select act_as('00000000-0000-4000-8000-000000000002');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')->>'source'='base','member may use explicitly eligible base');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','voz') is null,'base never shares owner ElevenLabs voice');
select act_as('00000000-0000-4000-8000-000000000001');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')->>'source'='personal','personal API remains first even while base enabled');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')::text like '%"source": "base"%','eligible base can follow personal alternatives');
select ai_my_key_set('groq',false);
select ai_my_key_set('xai',false);
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente')->>'source'='base','pausing own keys immediately revokes their use');
select ai_my_key_remove('groq');
select expect(ai_my_key_runtime('synthetic-server-proof-over-thirty-two-characters','groq') is null,'remove deletes sealed credential');
select act_as('00000000-0000-4000-8000-00000000000a');
select ai_save_provider('groq',true,'Owner main','','','','v1.replaced-main','repl');
select act_as('00000000-0000-4000-8000-000000000002');
select expect(ai_runtime_for_current('synthetic-server-proof-over-thirty-two-characters','assistente') is null,'credential replacement invalidates sharing approval');
select act_as('00000000-0000-4000-8000-00000000000a');
select set_config('test.reserve',ai_save_connection_details(null,'mistral','Independent',true,1,'v1.reserve','rese','','','')::text,false);
select ai_save_route('assistente','mistral',current_setting('test.reserve')::uuid,'auto:rapido',true,'fixed','[]');
select ai_save_route('organizar','groq',null,'auto:rapido',true,'fallback',jsonb_build_array(jsonb_build_object('connection_id',current_setting('test.reserve'),'model','auto:rapido')));
select ai_set_member_base_source('mistral',current_setting('test.reserve')::uuid,'no_training');
select ai_remove_connection(current_setting('test.reserve')::uuid);
select expect((select not enabled and connection_id is null from jsonb_to_recordset(ai_admin_state()->'tasks') as task(id text,enabled boolean,connection_id uuid) where id='assistente'),'deleting reserve pauses its direct task');
select expect((select jsonb_array_length(fallbacks)=0 from jsonb_to_recordset(ai_admin_state()->'tasks') as task(id text,fallbacks jsonb) where id='organizar'),'deleting reserve removes dangling fallback references');
select ai_remove_provider('groq');
select expect((select not has_key and not enabled from jsonb_to_recordset(ai_admin_state()->'providers') as p(id text,has_key boolean,enabled boolean) where id='groq'),'explicit main deletion clears the stored key');
select expect((select not enabled from jsonb_to_recordset(ai_admin_state()->'tasks') as task(id text,enabled boolean) where id='organizar'),'main deletion pauses tasks using the deleted key');
-- Personal account admission does not spend shared application counters.
reset role;
truncate private.jornada_request_limits,private.jornada_budget_days;
update private.jornada_global_budgets set minute_count=0;
set role authenticated;
select act_as('00000000-0000-4000-8000-000000000001');
select expect((app_consume_jornada_budget_source('synthetic-server-proof-over-thirty-two-characters','ai',1,'personal')->>'allowed')::boolean,'personal budget admits account');
reset role;
select expect((select sum(minute_count)=0 from private.jornada_global_budgets),'personal budget preserves shared application counters');
select expect((select day_count=1 from private.jornada_request_limits where user_id='00000000-0000-4000-8000-000000000001' and scope='ai'),'personal budget still increments account');
set role authenticated;
select act_as('00000000-0000-4000-8000-000000000001');
select expect((app_consume_jornada_budget_source('synthetic-server-proof-over-thirty-two-characters','ai',1,'base')->>'allowed')::boolean,'base source uses guarded shared counter');
do $$ begin perform app_consume_jornada_budget_source('synthetic-server-proof-over-thirty-two-characters','ai',1,'unknown'); raise exception 'FALHA: unknown source admission'; exception when invalid_parameter_value then null; end $$;
select messenger_create_code('telegram',encode(extensions.digest('member-link-code','sha256'),'hex'));
select act_as('00000000-0000-4000-8000-00000000000a');
select messenger_save('telegram',true,'synthetic_bot','v1.bot-token','bot',encode(extensions.digest('synthetic-server-proof-over-thirty-two-characters','sha256'),'hex'));
set role anon;
select expect(bot_link('synthetic-server-proof-over-thirty-two-characters','telegram','member-chat',encode(extensions.digest('member-link-code','sha256'),'hex')),'member may redeem own one-use bot code');
select expect(bot_context('synthetic-server-proof-over-thirty-two-characters','telegram','member-chat')->>'user_id'='00000000-0000-4000-8000-000000000001','member bot context belongs to code owner');
select expect(not bot_link('synthetic-server-proof-over-thirty-two-characters','telegram','foreign-chat',encode(extensions.digest('member-link-code','sha256'),'hex')),'bot code cannot be replayed');
select expect((bot_consume_jornada_budget_source('synthetic-server-proof-over-thirty-two-characters','telegram','member-chat','ai',1,'personal')->>'allowed')::boolean,'bot source budget follows linked member');
select expect(bot_context('synthetic-server-proof-over-thirty-two-characters','telegram','foreign-chat') is null,'unlinked bot chat cannot view another account');
do $$ begin perform ai_my_keys(); raise exception 'FALHA: anon vault metadata'; exception when insufficient_privilege then null; end $$;
reset role;
select 'OK: personal keys, eligible base, source budgets and deletion';
