import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('áreas e cadernos pessoais organizam notas e agenda sem exigir matéria', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Meu espaço', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Editar área Espiritualidade e propósito', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Nova área', exact: true }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Criatividade');
  await page.getByRole('button', { name: 'Salvar organização', exact: true }).click();
  await page.getByRole('button', { name: 'Novo caderno', exact: true }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Reflexões diárias');
  await page.getByLabel('Área do caderno').selectOption('emotional');
  await page.getByRole('button', { name: 'Salvar organização', exact: true }).click();
  const nav = page.getByRole('navigation', { name: 'Principal', exact: true });
  await nav.getByRole('button', { name: 'Caderno', exact: true }).click();
  await page.getByRole('button', { name: 'Nova anotação', exact: true }).click();
  await page.getByLabel('Título da anotação', { exact: true }).fill('Minha reflexão');
  await page.getByLabel('Caderno · opcional', { exact: true }).selectOption({ label: 'Reflexões diárias' });
  await page.getByLabel('Área da vida · opcional', { exact: true }).selectOption('emotional');
  await page.getByRole('button', { name: 'Salvar', exact: true }).click();
  await page.getByLabel('Filtrar caderno', { exact: true }).selectOption({ label: 'Reflexões diárias' });
  await expect(page.getByLabel('Título da anotação', { exact: true })).toHaveValue('Minha reflexão');
  await page.getByLabel('Filtrar caderno', { exact: true }).selectOption('__none');
  await expect(page.getByLabel('Título da anotação', { exact: true })).toHaveCount(0);
  await nav.getByRole('button', { name: 'Agenda', exact: true }).click();
  await page.getByRole('button', { name: 'Novo compromisso', exact: true }).click();
  await page.getByLabel('O que você quer fazer?', { exact: true }).fill('Consulta de rotina');
  await page.getByLabel('Área da vida · opcional', { exact: true }).selectOption('health');
  await page.getByLabel('Tipo', { exact: true }).selectOption('Consulta');
  await page.getByRole('button', { name: 'Salvar', exact: true }).click();
  await page.getByLabel('Filtrar área da vida', { exact: true }).selectOption('health');
  await expect(page.getByRole('button').filter({ hasText: 'Sem horário · Consulta' })).toContainText('Consulta de rotina');
  await page.getByLabel('Filtrar área da vida', { exact: true }).selectOption('work');
  await expect(page.getByRole('button').filter({ hasText: 'Sem horário · Consulta' })).toHaveCount(0);
  await page.reload();
  await nav.getByRole('button', { name: 'Caderno', exact: true }).click();
  await page.getByLabel('Filtrar caderno', { exact: true }).selectOption({ label: 'Reflexões diárias' });
  await expect(page.getByLabel('Título da anotação', { exact: true })).toHaveValue('Minha reflexão');
  await expect(page.getByLabel('Área da anotação', { exact: true })).toHaveValue('emotional');
  await page.getByRole('button', { name: 'Gerenciar áreas e cadernos', exact: true }).click();
  await page.getByRole('button', { name: 'Editar caderno Reflexões diárias', exact: true }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Meu diário');
  await page.getByRole('button', { name: 'Salvar organização', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Editar caderno Meu diário', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Ocultar Criatividade', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mostrar Criatividade', exact: true })).toBeVisible();
  const audit = await new AxeBuilder({ page }).include('.life-organization').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(audit.violations.map(item => item.id)).toEqual([]);
  await page.screenshot({ path: 'test-results/life-organization-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: 'test-results/life-organization-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('caderno completo preserva mídia, marcas e correções manuais ao reabrir', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const media = '/api/note-media/11111111-1111-4111-8111-111111111111';
  const raw = JSON.stringify({ version: 1, subjects: [], tasks: [], sessions: [], notes: [{ id: 'editor-test', title: 'Caderno de teste', subjectId: '', content: `<p><strong>imbigo</strong> para revisar.</p><p><span style="color: #123456; font-size: 24px">Texto colorido</span></p><img src="${media}.png" alt="Lousa de teste" width="75%"><audio src="${media}.mp3" title="Áudio de teste" controls></audio>`, updatedAt: '2026-09-22T12:00:00Z' }] });
  await page.route('**/api/note-media/*.png', route => route.fulfill({ contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') }));
  await page.addInitScript(value => { if (!localStorage.getItem('faculdade-psi:personal:v1')) localStorage.setItem('faculdade-psi:personal:v1', value); }, raw);
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('button', { name: 'Caderno', exact: true }).click();
  const editor = page.getByRole('textbox', { name: 'Conteúdo da anotação', exact: true });
  await expect(editor.locator('img')).toHaveAttribute('src', `${media}.png`);
  await expect(editor.locator('audio')).toHaveAttribute('src', `${media}.mp3`);
  await expect(editor.locator('.spelling-issue').filter({ hasText: 'imbigo' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: /Ortografia · Português/ }).click();
  await page.getByRole('button', { name: 'imbigo', exact: true }).click();
  await page.getByRole('button', { name: 'umbigo', exact: true }).click();
  await expect(editor.locator('strong')).toHaveText('umbigo');
  await expect(editor.locator('span').filter({ hasText: 'Texto colorido' }).first()).toHaveCSS('color', 'rgb(18, 52, 86)');
  await editor.click(); await page.keyboard.press('Control+End'); await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Link', exact: true }).click();
  await page.getByLabel('Endereço do link').fill('javascript:alert(1)');
  await page.getByRole('button', { name: 'Salvar link', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Use um endereço completo' })).toBeVisible();
  await page.getByLabel('Endereço do link').fill('https://example.com/aula');
  await page.getByRole('button', { name: 'Salvar link', exact: true }).click();
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/aula');
  await page.getByRole('button', { name: 'Tabela', exact: true }).click();
  await expect(editor.locator('table')).toHaveCount(1);
  await page.getByLabel('Título da anotação', { exact: true }).fill('Caderno revisado');
  await page.reload();
  await page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('button', { name: 'Caderno', exact: true }).click();
  await expect(editor.locator('strong')).toHaveText('umbigo');
  await expect(editor.locator('img')).toHaveAttribute('src', `${media}.png`);
  await expect(editor.locator('audio')).toHaveAttribute('controls', '');
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com/aula');
  await expect(editor.locator('table')).toHaveCount(1);
  await expect(editor).toHaveCSS('font-size', '18px');
  await expect(page.getByLabel('Fotografar lousa')).toHaveAttribute('capture', 'environment');
  const audit = await new AxeBuilder({ page }).include('.rich-notebook').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) }))).toEqual([]);
  await page.screenshot({ path: 'test-results/notebook-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await page.screenshot({ path: 'test-results/notebook-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('leitura preserva backup anterior sem adicionar uma grade automática', async ({ page }) => {
  const old = JSON.stringify({ version: 1, subjects: [], tasks: [], sessions: [], notes: [{ id: 'mine', title: 'Conteúdo anterior', subjectId: '', content: '<p><strong>Minha anotação</strong></p>', updatedAt: '2026-09-22T12:00:00Z' }] });
  await page.addInitScript(raw => { if (!localStorage.getItem('faculdade-psi:personal:v1')) localStorage.setItem('faculdade-psi:personal:v1', raw); }, old);
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('button', { name: 'Caderno', exact: true }).click();
  await expect(page.getByLabel('Título da anotação', { exact: true })).toHaveValue('Conteúdo anterior');
  const editor = page.getByRole('textbox', { name: 'Conteúdo da anotação', exact: true });
  await expect(editor.locator('strong')).toHaveText('Minha anotação');
  expect(await page.evaluate(() => localStorage.getItem('faculdade-psi:personal:v1'))).toBe(old);
  await page.getByLabel('Título da anotação', { exact: true }).fill('Edição preservada');
  await expect(page.getByRole('status').filter({ hasText: 'Salvo neste navegador' })).toBeVisible();
  await page.reload();
  await page.getByRole('navigation', { name: 'Principal', exact: true }).getByRole('button', { name: 'Caderno', exact: true }).click();
  await expect(page.getByLabel('Título da anotação', { exact: true })).toHaveValue('Edição preservada');
  await expect(editor.locator('strong')).toHaveText('Minha anotação');
});

test('dados corrompidos não são sobrescritos', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('faculdade-psi:personal:v1', '{invalid'));
  await page.goto('/');
  await expect(page.getByRole('alert').filter({ hasText: 'Nada foi substituído' })).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('faculdade-psi:personal:v1'))).toBe('{invalid');
});

test('espaço vazio cadastra a primeira matéria e aula e preserva após recarregar', async ({ page }) => {
  await page.goto('/');
  const nav = page.getByRole('navigation', { name: 'Principal', exact: true });
  await expect(page.getByRole('button', { name: 'Jornada Plena — início', exact: true })).toBeVisible();
  await nav.getByRole('button', { name: 'Agenda', exact: true }).click();
  await page.getByRole('button', { name: 'Minha grade', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Adicionar horário', exact: true })).toBeDisabled();
  await expect(page.getByRole('dialog')).toContainText('Primeiro cadastre uma matéria');
  await page.keyboard.press('Escape');
  await nav.getByRole('button', { name: 'Matérias', exact: true }).click();
  await page.getByRole('button', { name: 'Nova matéria', exact: true }).click();
  await page.getByLabel('Nome da matéria').fill('Matéria particular de teste');
  await page.getByRole('button', { name: 'Salvar', exact: true }).click();
  await nav.getByRole('button', { name: 'Agenda', exact: true }).click();
  await page.getByRole('button', { name: 'Minha grade', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('Nenhum horário cadastrado');
  await page.getByRole('button', { name: 'Adicionar horário', exact: true }).click();
  await page.getByLabel('Dia da semana', { exact: true }).selectOption('3');
  await page.getByLabel('Início', { exact: true }).fill('18:10');
  await page.getByRole('button', { name: 'Salvar horário', exact: true }).click();
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('faculdade-psi:personal:v1')!).classes.length)).toBe(1);
  await page.reload();
  await nav.getByRole('button', { name: 'Agenda', exact: true }).click();
  await page.getByRole('button', { name: 'Minha grade', exact: true }).click();
  await page.getByRole('button', { name: /18:10.*Matéria particular de teste/ }).click();
  await expect(page.getByLabel('Dia da semana', { exact: true })).toHaveValue('3');
  await expect(page.getByLabel('Início', { exact: true })).toHaveValue('18:10');
  await expect(page.getByLabel('Término (opcional)', { exact: true })).toHaveValue('');
  await expect(page.getByLabel('Primeira aula (opcional)', { exact: true })).toHaveValue('');
});
